modbus:
  send_wait_time: 200ms
  uart_id: ${heatpump_uart_id}
  id: heatpump_modbus_id

modbus_controller:
- id: heatpump_modbus_controller
  address: ${heatpump_modbus_address}   ## address of the Modbus slave device on the bus
  modbus_id: heatpump_modbus_id
  update_interval: ${heatpump_update_interval}
  command_throttle: 50ms


.boolean_sensor: &boolean_sensor_anchor
  platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  register_type: discrete_input

.boolean_switch: &boolean_switch_anchor
  platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  register_type: coil

.analog_sensor: &analog_sensor_anchor
  platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  register_type: read
  accuracy_decimals: 0
  value_type: S_WORD

.integer_sensor: &integer_sensor_anchor
  platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  register_type: read
  accuracy_decimals: 0
  value_type: S_WORD

.analog_mult10_number: &analog_mult10_number_anchor
  platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  value_type: S_WORD
  multiply: 10.0
  step: 0.1

.integer_number: &integer_number_anchor
  platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  value_type: S_WORD

.analog_div10_sensor: &analog_div10_sensor_anchor
  platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  register_type: read
  accuracy_decimals: 1
  value_type: S_WORD
  filters:
    - multiply: 0.1

.integer_div10_sensor: &integer_div10_sensor_anchor
  platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  register_type: read
  accuracy_decimals: 1
  value_type: S_WORD
  filters:
    - multiply: 0.1

.analog_temperature_sensor: &analog_temperature_sensor_anchor
- platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  device_class: temperature
  register_type: read
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  value_type: S_WORD
  filters:
    - multiply: 0.1

.integer_temperature_sensor: &integer_temperature_sensor_anchor
- platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  device_class: temperature
  register_type: read
  unit_of_measurement: "°C"
  accuracy_decimals: 0
  value_type: S_WORD

.analog_pressure_sensor: &analog_pressure_sensor_anchor
- platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  device_class: pressure
  register_type: read
  unit_of_measurement: "bar"
  accuracy_decimals: 1
  value_type: S_WORD
  filters:
    - multiply: 0.1

.integer_power_sensor: &integer_power_sensor_anchor
- platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  device_class: power
  register_type: read
  unit_of_measurement: "W"
  accuracy_decimals: 0
  value_type: S_WORD

.integer_energy_sensor: &integer_power_energy_anchor
- platform: modbus_controller
  modbus_controller_id: heatpump_modbus_controller
  device_class: energy
  register_type: read
  unit_of_measurement: "kWh"
  accuracy_decimals: 0
  value_type: S_WORD

sensor: &heatpump_sensors
- <<: *analog_temperature_sensor_anchor
  name: "Brine Out"
  address: 1

- <<: *analog_temperature_sensor_anchor
  name: "Brine In"
  address: 2

- <<: *analog_temperature_sensor_anchor
  name: "Heating Out"
  address: 3

- <<: *analog_temperature_sensor_anchor
  name: "Heating In"
  address: 4

- <<: *analog_temperature_sensor_anchor
  name: "Compressor suction temperature"
  address: 5

- <<: *analog_pressure_sensor_anchor
  name: "Compressor suction pressure"
  address: 6

- <<: *analog_pressure_sensor_anchor
  name: "Compressor discharge pressure"
  address: 7
    
- <<: *analog_temperature_sensor_anchor
  name: "DHW Temperature"
  address: 8

- <<: *analog_temperature_sensor_anchor
  name: "Outside Temperature"
  address: 11

- <<: *analog_pressure_sensor_anchor
  name: "Pressure Brine"
  address: 13

- <<: *analog_pressure_sensor_anchor
  name: "Pressure Heating"
  address: 14

- <<: *analog_temperature_sensor_anchor
  name: "Brine Temperature Air Unit Outlet"
  address: 29

- <<: *analog_div10_sensor_anchor
  name: "COP"
  unit_of_measurement: "COP"
  address: 30

- <<: *analog_div10_sensor_anchor
  name: "PF"
  unit_of_measurement: "PF"
  address: 31

- <<: *analog_temperature_sensor_anchor
  name: "Cooling Delta-T from Dewpoint"
  address: 50

- <<: *analog_temperature_sensor_anchor
  name: "Condensation temperature"
  address: 94

- <<: *analog_temperature_sensor_anchor
  name: "Heating DG1 Setpoint"
  address: 97
  # undocumented register

- <<: *analog_temperature_sensor_anchor
  #name: "Cooling SG3 Setpoint (with EVU signal)"
  name: "Cooling Buffer Temperature"
  address: 130
  # undocumented register

- <<: *analog_temperature_sensor_anchor
  name: "Heating Buffer Temperature"
  address: 131
  # undocumented register

- <<: *analog_temperature_sensor_anchor
  name: "Superheat"
  address: 132

- <<: *analog_sensor_anchor
  name: "Expansion Valve Position"
  address: 133
  unit_of_measurement: "%"
  # poorly documented, should be analog_div10_sensor_anchor - but crosscheck with Th-Touch says it's not div10

- <<: *analog_temperature_sensor_anchor
  name: "Supply Temperature SG2"
  address: 194

- <<: *analog_temperature_sensor_anchor
  name: "Supply Temperature SG3"
  address: 195

- <<: *analog_temperature_sensor_anchor
  name: "Supply Temperature SG4"
  address: 196
  
- <<: *analog_temperature_sensor_anchor
  name: "Start Temperature DHW"
  address: 198
  
- <<: *analog_temperature_sensor_anchor
  name: "Evaporation Temperature"
  address: 199
  
- <<: *analog_temperature_sensor_anchor
  name: "Heating Buffer Tank Temperature"
  address: 200
  
- <<: *analog_temperature_sensor_anchor
  name: "Cooling Buffer Tank Temperature"
  address: 201
  
- <<: *analog_div10_sensor_anchor
  name: "EER"
  unit_of_measurement: "EER"
  address: 202

- <<: *analog_temperature_sensor_anchor
  name: "Compressor Discharge Temperature"
  address: 203
  
- <<: *integer_sensor_anchor
  name: "Compressor RPM"
  unit_of_measurement: "RPM"
  address: 5002

- <<: *integer_temperature_sensor_anchor
  name: "Scroll Temperature"
  address: 5004

- <<: *integer_temperature_sensor_anchor
  name: "Inverter Temperature"
  address: 5005

- <<: *integer_div10_sensor_anchor
  name: "Production Pump"
  address: 5033
  unit_of_measurement: "%"
  # in 0.1%; undocumented register

- <<: *integer_div10_sensor_anchor
  name: "Brine Pump"
  address: 5034
  unit_of_measurement: "%"
  # in 0.1%; undocumented register

- <<: *integer_sensor_anchor
  name: "EVU signal"
  address: 5066
  # undocumented register

- <<: *integer_sensor_anchor
  name: "Working Hours L"
  address: 5080
  internal: True
  id: working_hours_l
  value_type: U_WORD

- <<: *integer_sensor_anchor
  name: "Working Hours H"
  address: 5081
  internal: True
  id: working_hours_h
  value_type: U_WORD

- platform: template
  name: "Working Hours"
  lambda: |-
      return id(working_hours_h).state * 1000 + id(working_hours_l).state;
  accuracy_decimals: 0
  unit_of_measurement: "h"

- <<: *integer_power_sensor_anchor
  name: "Power Consumption"
  address: 5082

- <<: *integer_power_sensor_anchor
  name: "Condensation Capacity"
  address: 5083

- <<: *integer_sensor_anchor
  name: "Current Hour"
  address: 5093
  id: current_hour
  internal: True

- <<: *integer_sensor_anchor
  name: "Current Minute"
  address: 5094
  id: current_minute
  internal: True

- <<: *integer_sensor_anchor
  name: "Current Day"
  address: 5095
  id: current_day
  internal: True

- <<: *integer_sensor_anchor
  name: "Current Month"
  address: 5096
  id: current_month
  internal: True

- <<: *integer_sensor_anchor
  name: "Current Year"
  address: 5097
  id: current_year
  internal: True

- <<: *integer_power_energy_anchor
  name: "Condensation Energy January"
  address: 5144

- <<: *integer_power_energy_anchor
  name: "Condensation Energy February"
  address: 5145

- <<: *integer_power_energy_anchor
  name: "Condensation Energy March"
  address: 5146

- <<: *integer_power_energy_anchor
  name: "Condensation Energy April"
  address: 5147

- <<: *integer_power_energy_anchor
  name: "Condensation Energy May"
  address: 5148

- <<: *integer_power_energy_anchor
  name: "Condensation Energy June"
  address: 5149

- <<: *integer_power_energy_anchor
  name: "Condensation Energy July"
  address: 5150

- <<: *integer_power_energy_anchor
  name: "Condensation Energy August"
  address: 5151

- <<: *integer_power_energy_anchor
  name: "Condensation Energy September"
  address: 5152

- <<: *integer_power_energy_anchor
  name: "Condensation Energy October"
  address: 5153

- <<: *integer_power_energy_anchor
  name: "Condensation Energy November"
  address: 5154

- <<: *integer_power_energy_anchor
  name: "Condensation Energy December"
  address: 5155

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy January"
  address: 5156

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy February"
  address: 5157

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy March"
  address: 5158

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy April"
  address: 5159

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy May"
  address: 5160

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy June"
  address: 5161

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy July"
  address: 5162

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy August"
  address: 5163

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy September"
  address: 5164

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy October"
  address: 5165

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy November"
  address: 5166

- <<: *integer_power_energy_anchor
  name: "Evaporation Energy December"
  address: 5167

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption January"
  address: 5168

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption February"
  address: 5169

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption March"
  address: 5170

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption April"
  address: 5171

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption May"
  address: 5172

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption June"
  address: 5173

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption July"
  address: 5174

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption August"
  address: 5175

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption September"
  address: 5176

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption October"
  address: 5177

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption November"
  address: 5178

- <<: *integer_power_energy_anchor
  name: "Electrical Consumption December"
  address: 5179

- <<: *integer_power_sensor_anchor
  name: "Evaporation Capacity"
  address: 5185

- <<: *integer_sensor_anchor
  name: "Working Program by BUS"
  address: 5221
  # 0 - mixed, 1 - heating, 2 - cooling, 3 - off

- <<: *integer_sensor_anchor
  name: "BUS DHW Demand"
  address: 5222
  # 0 - off, 1 - on

- <<: *integer_sensor_anchor
  name: "BUS Pool Demand"
  address: 5223
  # 0 - off, 1 - on

- <<: *integer_sensor_anchor
  name: "BUS DG1 Demand"
  address: 5224
  # 0 - off, 1 - on

- <<: *integer_sensor_anchor
  name: "BUS SG2 Demand"
  address: 5225
  # 0 - off, 1 - on

- <<: *integer_sensor_anchor
  name: "BUS SG3 Demand"
  address: 5226
  # 0 - off, 1 - on

- <<: *integer_sensor_anchor
  name: "BUS SG4 Demand"
  address: 5227
  # 0 - off, 1 - on

- <<: *integer_sensor_anchor
  name: "Number Of Starts L"
  address: 5281
  id: starts_l
  internal: True
  value_type: U_WORD

- <<: *integer_sensor_anchor
  name: "Number Of Starts H"
  address: 5282
  id: starts_h
  internal: True
  value_type: U_WORD

- platform: template
  name: "Number Of Starts"
  lambda: |-
      return id(starts_h).state * 10000 + id(starts_l).state;
  accuracy_decimals: 0
  unit_of_measurement: "Starts"

- <<: *integer_sensor_anchor
  name: "Software version 1"
  address: 5285
  id: sw_version_1
  internal: True

- <<: *integer_sensor_anchor
  name: "Software version 2"
  address: 5286
  id: sw_version_2
  internal: True

- <<: *integer_sensor_anchor
  name: "Software version 3"
  address: 5287
  id: sw_version_3
  internal: True

text_sensor: &heatpump_text_sensors
- platform: template
  name: "Current Time"
  lambda: |-
      char str[20];
      time_t currTime;
      struct tm now = {
        .tm_min  = int(id(current_minute).state),
        .tm_hour = int(id(current_hour).state),
        .tm_mday = int(id(current_day).state),
        .tm_mon  = int(id(current_month).state) - 1, // counts from 1 to 12, while tm counts from 0 to 11.
        .tm_year = 100 + int(id(current_year).state), // reference year 2000 instead of 1900.
      };
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M", &now);
      return std::string(str);

- platform: template
  name: "Software version"
  lambda: |-
      char str[20];
      sprintf(str, "%d.%d.%d", int(id(sw_version_1).state), int(id(sw_version_2).state), int(id(sw_version_3).state));
      return std::string(str);
  

number: &heatpump_numbers
- <<: *analog_mult10_number_anchor
  name: "Delta-T Start DHW"
  address: 15
  min_value: 0
  max_value: 20
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "DHW Setpoint"
  address: 17
  min_value: 0
  max_value: 80
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Pool Heating Setpoint"
  address: 19
  min_value: 0
  max_value: 80
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Min Allowed Brine Temp"
  address: 24
  min_value: -20
  max_value: 20
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Heating Curve Min Production & Max Outside Temperature"
  address: 34
  min_value: -20
  max_value: 40
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Heating Curve Min Outside Temperature"
  address: 35
  min_value: -20
  max_value: 40
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Heating Curve Max Production Temperature"
  address: 36
  min_value: -20
  max_value: 40
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Heating Fixed Temperature"
  address: 73
  min_value: 0
  max_value: 40
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Thermal Power DHW Min"
  address: 74
  min_value: 15
  max_value: 100
  unit_of_measurement: "%"
  # undocumented register

- <<: *analog_mult10_number_anchor
  name: "Thermal Power DHW Max"
  address: 75
  min_value: 15
  max_value: 100
  unit_of_measurement: "%"
  # undocumented register

- <<: *analog_mult10_number_anchor
  name: "Thermal Power Heating Min"
  address: 76
  min_value: 15
  max_value: 100
  unit_of_measurement: "%"
  # undocumented register

- <<: *analog_mult10_number_anchor
  name: "Thermal Power Heating Max"
  address: 77
  min_value: 15
  max_value: 100
  unit_of_measurement: "%"
  # undocumented register

- <<: *analog_mult10_number_anchor
  name: "Min Allowed Production Temp"
  address: 87
  min_value: -20
  max_value: 20
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Production Pump Min"
  address: 90
  min_value: 0
  max_value: 100
  unit_of_measurement: "%"
  # undocumented register

- <<: *analog_mult10_number_anchor
  name: "Production Pump Max"
  address: 91
  min_value: 0
  max_value: 100
  unit_of_measurement: "%"
  # undocumented register

- <<: *analog_mult10_number_anchor
  name: "BUS DHW Setpoint"
  address: 134
  min_value: 0
  max_value: 80
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "BUS Heating DG1 Setpoint"
  address: 135
  min_value: 20
  max_value: 40
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "BUS Heating SG2 Setpoint"
  address: 136
  min_value: 20
  max_value: 40
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "BUS Heating SG3 Setpoint"
  address: 137
  min_value: 20
  max_value: 40
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "BUS Heating SG4 Setpoint"
  address: 138
  min_value: 20
  max_value: 40
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "BUS Cooling DG1 Setpoint"
  address: 139
  min_value: 5
  max_value: 30
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "BUS Cooling SG2 Setpoint"
  address: 140
  min_value: 5
  max_value: 30
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "BUS Cooling SG3 Setpoint"
  address: 141
  min_value: 5
  max_value: 30
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "BUS Cooling SG4 Setpoint"
  address: 142
  min_value: 5
  max_value: 30
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "BUS Pool Setpoint"
  address: 143
  min_value: 20
  max_value: 40
  device_class: temperature
  unit_of_measurement: "°C"

- <<: *analog_mult10_number_anchor
  name: "Delta-T Start Heating"
  address: 154
  min_value: 0
  max_value: 20
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Delta-T Start Cooling"
  address: 156
  min_value: 0
  max_value: 20
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *analog_mult10_number_anchor
  name: "Max Allowed Brine Temp"
  address: 161
  min_value: -20
  max_value: 20
  device_class: temperature
  unit_of_measurement: "°C"
  # undocumented register - range is guessed

- <<: *integer_number_anchor
  name: "Mode"
  address: 5058
  min_value: 0
  max_value: 2
  # 0 - off, 1 - on, 2 - emergency
  # undocumented register - range is guessed


binary_sensor: &heatpump_binary_sensors
- <<: *boolean_sensor_anchor
  name: "Alarm"
  address: 50
  filters:
    invert:

- <<: *boolean_sensor_anchor
  name: "Summer"
  address: 127

- <<: *boolean_sensor_anchor
  name: "Winter"
  address: 128

switch: &heatpump_switches
- <<: *boolean_switch_anchor
  name: "control by BUS"
  address: 53

#- <<: *boolean_switch_anchor
#  name: "DHW remote by installer"
#  address: 49
#  # undocumented register

#- <<: *boolean_switch_anchor
#  name: "DHW enable by installer"
#  address: 64
#  # undocumented register

- <<: *boolean_switch_anchor
  name: "DHW Enable"
  address: 106
  # undocumented register

- <<: *boolean_switch_anchor
  name: "DHW Remote Enable"
  address: 122
  # undocumented register

- <<: *boolean_switch_anchor
  name: "Control DG1"
  address: 118
  # 0 - fixed  temp, 1 - heating curve
  # undocumented register
